# Generated by Django 2.0.5 on 2018-10-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postchat',
            name='uuid',
            field=models.CharField(default='940b506aecd5489d976d49c1666e6f16', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postchatrestmessage',
            name='uuid',
            field=models.CharField(default='0fc41544b9a140afa5ea254d6460db41', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='uuid',
            field=models.CharField(default='a81e4cf30c794ebeb59c4c4b76b745b0', max_length=34, unique=True),
        ),
    ]
